modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/TntSlimes/issues"
license="MIT"

[[mods]]
modId="tntslimes"
version="${file.jarVersion}"
displayName="TNT Slimes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tnt-slimes"
authors="Mrbysco, Darkosto"
description='''
Wait, are you gonna tell me slimes can't hold TNT?
'''
[[dependencies.tntslimes]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.tntslimes]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"