modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Mrbysco/TntSlimes/issues"
license="MIT"

[[mods]]
modId="tntslimes"
version="${file.jarVersion}"
displayName="TNT Slimes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tnt-slimes"
authors="Mrbysco, Darkosto"
description='''
Wait, are you gonna tell me slimes can't hold TNT?
'''
[[dependencies.tntslimes]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"