modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/TntSlimes/issues"
license="MIT"

[[mods]]
modId="tntslimes"
version="${file.jarVersion}"
displayName="TNT Slimes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tnt-slimes"
authors="Mrbysco, Darkosto"
description='''
Wait, are you gonna tell me slimes can't hold TNT?
'''
[[dependencies.tntslimes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.tntslimes]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"