modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/TntSlimes/issues"
license="MIT"

[[mods]]
modId="tntslimes"
version="${file.jarVersion}"
displayName="TNT Slimes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tnt-slimes"
authors="Mrbysco, Darkosto"
description='''
Wait, are you gonna tell me slimes can't hold TNT?
'''
[[dependencies.tntslimes]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.tntslimes]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"